spring:
  profiles:
    active: dev

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yellowstone?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: dustjr12@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  config:
    activate:
      on-profile: dev

server:
  port: 9000

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

---
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  config:
    activate:
      on-profile: dev

server:
  port: 9000

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
